#!/usr/bin/env sh

# Gradle start up script for POSIX generated by Gradle.

APP_HOME=$(cd "${0%/*}" && pwd -P)

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
  echo "Gradle wrapper jar not found. Please run 'gradle wrapper' or let Android Studio regenerate it." >&2
  exit 1
fi

exec java -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
